### ISSUE TITLE
Log to sentry in case of Solr errors.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/ftw.solr#161]
Currently errors that occur when communicating with solr are logged in `solr.log` (or to the console in case of maintenance). We don't see those errors in sentry and thus are not actively notified of them. Especially for errors that occur in production with single documents it would be handy to have them in sentry.
Solr is becoming more and more critical for certain of our deployments, so we should be actively notified of errors.

We should think about including sentry logging in case of non-ok responses from solr, e.g. in:

https://github.com/4teamwork/ftw.solr/blob/8354f7658a9e301854d671e3d478923509fa55fe/ftw/solr/connection.py#L148

**Comment by buchi** [comment]
This is not true. `solr.log` is the log file of the Solr server. ftw.solr uses Python's logging facility and thus logs where Zope is configured to log to.

I'm against having any Sentry specific code here. If these errors don't show up in Sentry, then it's because of a misconfiguration of the Sentry integration. I suspect that only exceptions are logged to Sentry. But this is not the default, so it's an issue with our Sentry integration.

**Comment by deiferni** [comment]
Ok thanks for the feedback. Will double-check.

**Comment by njohner** [comment]
Moved to Jira: https://4teamwork.atlassian.net/browse/GEVER-182
